# Generated by Django 3.1.1 on 2020-09-22 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio_Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('E_mail', models.EmailField(max_length=254, null=True)),
                ('recorrido', models.TextField()),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateTimeField()),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('permitir_comentarios', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('fecha_viaje', models.DateTimeField()),
                ('fecha_lapso', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('permitir_comentarios', models.BooleanField(default=True)),
                ('E_mail', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=20, null=True, verbose_name='Nro Telefono')),
                ('localidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_destino', to='Anuncio.localidad')),
                ('localidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_origen', to='Anuncio.localidad')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anuncio.anuncio_trans')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio_trans',
            name='localidad_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_destino_trans', to='Anuncio.localidad'),
        ),
        migrations.AddField(
            model_name='anuncio_trans',
            name='localidad_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_origen_trans', to='Anuncio.localidad'),
        ),
        migrations.AddField(
            model_name='anuncio_trans',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anuncio.transporte'),
        ),
        migrations.AddField(
            model_name='anuncio_trans',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
