# Generated by Django 3.1.1 on 2020-09-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateTimeField()),
                ('rutas', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('transporte', models.CharField(max_length=100)),
                ('localidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_destino', to='Anuncio.localidad')),
                ('localidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_origen', to='Anuncio.localidad')),
            ],
        ),
    ]
