# Generated by Django 3.1.1 on 2020-09-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='rutas',
            new_name='recorrido',
        ),
    ]
