# Generated by Django 3.1.1 on 2020-09-25 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0002_auto_20200924_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionpost',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
