# Generated by Django 3.1.1 on 2020-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0002_auto_20200915_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='nombre',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='recorrido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='transporte',
            field=models.BooleanField(default=True),
        ),
    ]
