# Generated by Django 3.1.1 on 2020-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0003_auto_20200925_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio_trans',
            name='E_mail',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='anuncio_trans',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
