# Generated by Django 3.1.1 on 2020-09-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0003_auto_20200916_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='Anuncio.transporte'),
        ),
    ]
