# Generated by Django 3.1.1 on 2020-09-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0005_auto_20200917_1156'),
        ('Anuncio', '0006_anuncio_contratista'),
    ]

    operations = [
    ]
