# Generated by Django 3.1.1 on 2020-09-19 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0007_merge_20200918_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio_Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('recorrido', models.TextField()),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateTimeField()),
                ('tel', models.IntegerField()),
                ('localidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_destino_trans', to='Anuncio.localidad')),
                ('localidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_origen_trans', to='Anuncio.localidad')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anuncio.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('fecha_viaje', models.DateTimeField()),
                ('fecha_lapso', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('localidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_destino', to='Anuncio.localidad')),
                ('localidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_origen', to='Anuncio.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='anuncio_contratista',
            name='localidad_destino',
        ),
        migrations.RemoveField(
            model_name='anuncio_contratista',
            name='localidad_origen',
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
        migrations.DeleteModel(
            name='Anuncio_contratista',
        ),
        migrations.AddField(
            model_name='contratista',
            name='tipo_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anuncio.servicios'),
        ),
    ]
