# Generated by Django 3.1.1 on 2020-09-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0008_auto_20200918_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anuncio_Trans',
            new_name='Anuncio_Transportista',
        ),
    ]
