# Generated by Django 3.1.1 on 2020-09-19 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Anuncio', '0010_auto_20200919_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio_trans',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
