# Generated by Django 3.1.1 on 2020-09-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0012_auto_20200919_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario_contra',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='comentario_contra',
            old_name='anuncio',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comentario_contra',
            old_name='comentario',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='comentario_trans',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='comentario_trans',
            old_name='anuncio',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comentario_trans',
            old_name='comentario',
            new_name='texto',
        ),
    ]
