# Generated by Django 3.1.1 on 2020-09-20 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Anuncio', '0016_auto_20200919_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario_contra',
            new_name='Comentario',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anuncio.anuncio_trans'),
        ),
        migrations.DeleteModel(
            name='Comentario_trans',
        ),
    ]
