# Generated by Django 3.1.1 on 2020-09-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncio', '0017_auto_20200919_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='anuncio',
        ),
    ]
