# Generated by Django 3.1 on 2020-09-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
