# Generated by Django 3.1.1 on 2020-09-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Dni',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='Domicilio',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='Email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='Tel',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
