# Generated by Django 3.1 on 2020-09-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200921_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='Dni',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='Domicilio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='Tel',
        ),
    ]
